config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  post '/sessions' => "sessions#create"
  delete '/' => "sessions#destroy", as: 'logout'
  get '/sessions' => "sessions#new"
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :fname, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :lname, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :ename, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates_uniqueness_of :email
  validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @error
    user = User.find_by_email(userparams[:email])
    if user && user.authenticate(userparams[:password])
      session[:type]=user.role
      if user.role=='admin'
        redirect_to '/users'
      else
        session[:id]=user.id
        redirect_to user
      end
    else
      @error = "invalid credentials"
      render 'new'
    end
  end

  def destroy
    session[:type]=nil
    render 'new'
  end

  private

  def userparams
    params.require(:user).permit(:email, :password)
  end

  def is_admin?
    unless session[:type]=='admin'
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :new, :create]
  before_action :is_admin?, except: [:show]
  before_action :is_user?, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @error
    @user = User.new(userparams)
    if @user.save
      redirect_to @user
    else
      @error="Enter valid email id and correct password"
      render 'new'
    end
  end

  def edit
  end

  def update
    @error
    if @user.update(userparams)
      redirect_to @user
    else
      @error="Enter valid email id and correct password"
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user.delete
    redirect_to '/users'
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def userparams
    params.require(:user).permit(:fname,:lname,:dob,:doj,:sal,:contact,:bloodtype,:address,:city,:state,:gender,:notice,
    :country,:pincode,:ename,:relation,:econtact,:pskill,:sskill1,:sskill2,:role,:email,:password,:password_confirmation)
  end

  def is_admin?
    unless session[:type]=='admin'
      redirect_to root_path
    end
  end

  def is_user?
    unless session[:id]==@user.id || session[:type]=='admin'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FroalaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Froala Design Blocks - Headers</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link type="text/css" rel="stylesheet" href="css/froala_blocks.css">
    <link href='https://fonts.googleapis.com/css?family=Bebas Neue' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      html {
        height: 100%;
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }
      body {
        background-color: #222222;
        background: repeating-linear-gradient(45deg, #2b2b2b 0%, #2b2b2b 10%, #222222 0%, #222222 50%) 0 / 15px 15px;
        position: relative;
        margin: 0;
        padding-bottom: 6rem;
        min-height: 100%;
        font-family: "Helvetica Neue", Arial, sans-serif;
      }

      .font-beba {
          font-family: 'Bebas Neue';font-size: 45px;
          color: white;
          text-align: center;
      }


    </style>
    <script>
      var page = window.location.pathname.split('/')
      page = page[page.length - 1]

      var nav = document.querySelector('a[href="' + page + '"]')
      if (nav) {
        nav.classList.add('active')
      }

    </script>
  </head>

  <body>
    <header class="bg-light">
      <div class="container">
        <nav class="navbar navbar-expand-md">
          <a class="navbar-brand" href="/users">
            <img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="40" alt="image">
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav9" aria-controls="navbarNav9" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav9">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/users">Home <span class="sr-only">(current)</span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="/users/new">Registration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#footer">Contact Us</a>
              </li>
            </ul>

            <ul class="navbar-nav justify-content-end d-none d-lg-flex ml-md-auto">
              <li class="nav-item active">
                <a class="nav-link" href="https://www.facebook.com/exalogicsolns/"><i class="fab fa-facebook"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://in.linkedin.com/company/exalogic-solutions"><i class="fab fa-linkedin"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/exalogicsolns"><i class="fab fa-twitter"></i></a>
              </li>
            </ul>
            <%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-outline-dark ml-md-3"%>
          </div>
        </nav>
      </div>
    </header>

    <div class="container">
      <pre>

<div class="font-beba">EDIT USER</div><%= render "form"%>


      </pre>
    </div>

    <div class="footer" id="footer">
<pre><h4>EXALOGIC SOLUTIONS</h4>No 21, 1st Main, Ganga nagar, Bangalore
Karnataka, India - 560032<table align='center'>
<tr>
  <td><i class="fa fa-globe" aria-hidden="true">  </i></td><td><a href="http://www.exalogic.in/">www.exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-envelope" aria-hidden="true">  </i></td><td><a href="mailto:info@exalogic.in?subject=query">info@exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-phone" aria-hidden="true">  </i></td><td><a href="tel:080- 48905017">080- 48905017</a></td>
</tr>
</table></pre>
<a href="#"><i class="fa fa-arrow-up fa-2x" aria-hidden="true"></i></a>
    </div>
  </body>

</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Froala Design Blocks - Headers</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link type="text/css" rel="stylesheet" href="css/froala_blocks.css">
    <link href='https://fonts.googleapis.com/css?family=Bebas Neue' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Titillium Web' rel='stylesheet'>
    <style>
      html {
        height: 100%;
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }
      body {
        background-color: #222222;
        background: repeating-linear-gradient(45deg, #2b2b2b 0%, #2b2b2b 10%, #222222 0%, #222222 50%) 0 / 15px 15px;
        position: relative;
        margin: 0;
        padding-bottom: 6rem;
        min-height: 100%;
        font-family: "Helvetica Neue", Arial, sans-serif;
      }


    </style>
    <script>
      var page = window.location.pathname.split('/')
      page = page[page.length - 1]

      var nav = document.querySelector('a[href="' + page + '"]')
      if (nav) {
        nav.classList.add('active')
      }

    </script>
  </head>

  <body>
    <header class="bg-light">
      <div class="container">
        <nav class="navbar navbar-expand-md">
          <a class="navbar-brand" href="#">
            <img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="40" alt="image">
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav9" aria-controls="navbarNav9" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav9">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/users/new">Registration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#footer">Contact Us</a>
              </li>
            </ul>

            <ul class="navbar-nav justify-content-end d-none d-lg-flex ml-md-auto">
              <li class="nav-item active">
                <a class="nav-link" href="https://www.facebook.com/exalogicsolns/"><i class="fab fa-facebook"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://in.linkedin.com/company/exalogic-solutions"><i class="fab fa-linkedin"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/exalogicsolns"><i class="fab fa-twitter"></i></a>
              </li>
            </ul>
            <%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-outline-dark ml-md-3"%>
          </div>
        </nav>
      </div>
    </header>
    <br>
    <div class="container">
      <br><br>


                <% i=0%>
                <table>
                  <tr>
                    <td colspan="3" align="center">
                      <div class="cont">
                      <div class="font-bebas">
                        <i class="fas fa-user-circle fa-3x"></i><br>
                        USERS COUNT<br>
                        <%= User.count-1%>
                      </div>
                    </div>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="3" style="text-align:center;"><div class="font-beba">USERS</div></td>
                  </tr>
                  <% @users.each do |user|%>
                    <% if user.role!='admin'%>
                      <% if i%3==0%>
                        <tr>
                          <td>
                            <a href="<%= "/users/" << user.id.to_s%>">
	<div class="card">
        	<% if user.gender=='Male'%>
                	<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                <%elsif user.gender=='Female'%>
                	<img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                <% else%>
			<img src="assets/user-icon.jpg" alt="Avatar" style="width:100%">
		<% end%>
                <div class="container-card">
                	<h4><b><%= user.fname%></b></h4>
                        <p><%= user.email%></p>
                </div>
        </div>
</a>

                          </td>
                      <% elsif i%3==1%>
                          <td>
                            <a href="<%= "/users/" << user.id.to_s%>">
	<div class="card">
        	<% if user.gender=='Male'%>
                	<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                <%elsif user.gender=='Female'%>
                	<img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                <% else%>
			<img src="assets/user-icon.jpg" alt="Avatar" style="width:100%">
		<% end%>
                <div class="container-card">
                	<h4><b><%= user.fname%></b></h4>
                        <p><%= user.email%></p>
                </div>
        </div>
</a>
                          </td>
                      <% else%>
                          <td>
                            <a href="<%= "/users/" << user.id.to_s%>">
	<div class="card">
        	<% if user.gender=='Male'%>
                	<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                <%elsif user.gender=='Female'%>
                	<img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                <% else%>
			<img src="assets/user-icon.jpg" alt="Avatar" style="width:100%">
		<% end%>
                <div class="container-card">
                	<h4><b><%= user.fname%></b></h4>
                        <p><%= user.email%></p>
                </div>
        </div>
</a>
                          </td>
                        </tr>
                      <% end%>
                      <% i+=1%>
                    <% end%>
                  <% end%>
                </table>

              <% @users.each do |user|%>
                  <pre>

                  </pre>
              <% end%>
    </div>
    <div class="footer" id="footer">
<pre><h4>EXALOGIC SOLUTIONS</h4>No 21, 1st Main, Ganga nagar, Bangalore
Karnataka, India - 560032<table align='center'>
<tr>
  <td><i class="fa fa-globe" aria-hidden="true">  </i></td><td><a href="http://www.exalogic.in/">www.exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-envelope" aria-hidden="true">  </i></td><td><a href="mailto:info@exalogic.in?subject=query">info@exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-phone" aria-hidden="true">  </i></td><td><a href="tel:080- 48905017">080- 48905017</a></td>
</tr>
</table></pre>
<a href="#"><i class="fa fa-arrow-up fa-2x" aria-hidden="true"></i></a>
    </div>
  </body>

</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Froala Design Blocks - Headers</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link type="text/css" rel="stylesheet" href="css/froala_blocks.css">
    <link href='https://fonts.googleapis.com/css?family=Bebas Neue' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      html {
        height: 100%;
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }
      body {
        background-color: #222222;
        background: repeating-linear-gradient(45deg, #2b2b2b 0%, #2b2b2b 10%, #222222 0%, #222222 50%) 0 / 15px 15px;
        position: relative;
        margin: 0;
        padding-bottom: 6rem;
        min-height: 100%;
        font-family: "Helvetica Neue", Arial, sans-serif;
      }



    </style>
    <script>
      var page = window.location.pathname.split('/')
      page = page[page.length - 1]

      var nav = document.querySelector('a[href="' + page + '"]')
      if (nav) {
        nav.classList.add('active')
      }

    </script>
  </head>

  <body>
    <header class="bg-light">
      <div class="container">
        <nav class="navbar navbar-expand-md">
          <a class="navbar-brand" href="/users">
            <img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="40" alt="image">
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav9" aria-controls="navbarNav9" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav9">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/users">Home <span class="sr-only">(current)</span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="/users/new">Registration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#footer">Contact Us</a>
              </li>
            </ul>

            <ul class="navbar-nav justify-content-end d-none d-lg-flex ml-md-auto">
              <li class="nav-item active">
                <a class="nav-link" href="https://www.facebook.com/exalogicsolns/"><i class="fab fa-facebook"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://in.linkedin.com/company/exalogic-solutions"><i class="fab fa-linkedin"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/exalogicsolns"><i class="fab fa-twitter"></i></a>
              </li>
            </ul>
            <%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-outline-dark ml-md-3"%>
          </div>
        </nav>
      </div>
    </header>

    <div class="container">
      <pre>

<div class="font-beba">REGISTRATION FORM</div><%= render "form"%>
<font color="white"><span><% @error%></span></font>

      </pre>
    </div>

    <div class="footer" id="footer">
<pre><h4>EXALOGIC SOLUTIONS</h4>No 21, 1st Main, Ganga nagar, Bangalore
Karnataka, India - 560032<table align='center'>
<tr>
  <td><i class="fa fa-globe" aria-hidden="true">  </i></td><td><a href="http://www.exalogic.in/">www.exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-envelope" aria-hidden="true">  </i></td><td><a href="mailto:info@exalogic.in?subject=query">info@exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-phone" aria-hidden="true">  </i></td><td><a href="tel:080- 48905017">080- 48905017</a></td>
</tr>
</table></pre>
<a href="#"><i class="fa fa-arrow-up fa-2x" aria-hidden="true"></i></a>
    </div>
  </body>

</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Froala Design Blocks - Headers</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link type="text/css" rel="stylesheet" href="css/froala_blocks.css">
    <link href='https://fonts.googleapis.com/css?family=Bebas Neue' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      html {
        height: 100%;
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }
      body {
        background-color: #222222;
        background: repeating-linear-gradient(45deg, #2b2b2b 0%, #2b2b2b 10%, #222222 0%, #222222 50%) 0 / 15px 15px;
        position: relative;
        margin: 0;
        padding-bottom: 6rem;
        min-height: 100%;
        font-family: "Helvetica Neue", Arial, sans-serif;
      }




    </style>
    <script>
      var page = window.location.pathname.split('/')
      page = page[page.length - 1]

      var nav = document.querySelector('a[href="' + page + '"]')
      if (nav) {
        nav.classList.add('active')
      }

    </script>
  </head>

  <body>
    <header class="bg-light">
      <div class="container">
        <nav class="navbar navbar-expand-md">
          <% if session[:type]=='admin'%>
          <a class="navbar-brand" href="/users">
            <img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="40" alt="image">
          </a>
          <% else%>
          <a class="navbar-brand" href="#">
            <img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="40" alt="image">
          </a>
          <% end%>


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav9" aria-controls="navbarNav9" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav9">
            <% if session[:type]=='admin'%>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/users">Home <span class="sr-only">(current)</span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="/users/new">Registration</a>
              </li>
            <% else%>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
            <% end%>
              <li class="nav-item">
                <a class="nav-link" href="#footer">Contact Us</a>
              </li>
            </ul>

            <ul class="navbar-nav justify-content-end d-none d-lg-flex ml-md-auto">
              <li class="nav-item active">
                <a class="nav-link" href="https://www.facebook.com/exalogicsolns/"><i class="fab fa-facebook"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://in.linkedin.com/company/exalogic-solutions"><i class="fab fa-linkedin"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/exalogicsolns"><i class="fab fa-twitter"></i></a>
              </li>
            </ul>
            <%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-outline-dark ml-md-3"%>
          </div>
        </nav>
      </div>
    </header>

    <div class="container">
      <pre>
<div class="font-beba">
  <%= @user.fname%></div><div class="font-beba-small">
  <table class="table table-striped table-dark">
            <tr>
              <td>First Name</td><td><%= @user.fname%></td>
              <td>Last Name</td><td><%= @user.lname%></td>
            </tr>
            <tr>
              <td>Date of Birth</td><td><%= @user.dob%></td>
              <% if @user.dob!=nil%>
                <td>Age</td><td><%= ((Date.today-@user.dob.to_date)/365).to_i%></td>
              <% else%>
                <td>Age</td><td></td>
              <% end%>
            </tr>
            <tr>
              <td>Date of Joining</td><td><%= @user.doj%></td>
              <td>Blood Group</td><td><%= @user.bloodtype%></td>
            </tr>
            <tr>
              <td>Salary per annum</td><td><%= (@user.sal).to_i%></td>
              <% if @user.sal!=nil%>
                <td>Salary per month</td><td><%= (@user.sal/12).to_i%></td>
              <% else%>
                <td>Salary per month</td><td></td>
              <% end%>
            </tr>
            <tr>
              <td>Contact</td><td><%= @user.contact%></td>
              <td>Email</td><td><%= @user.email%></td>
            </tr>
            <tr>
              <td>Address</td><td><%= @user.address%></td>
              <td>City</td><td><%= @user.city%></td>
            </tr>
            <tr>
              <td>State</td><td><%= @user.state%></td>
              <td>Country</td><td><%= @user.country%></td>
            </tr>
            <tr>
              <td>Pincode</td><td><%= @user.pincode%></td>
              <td>Notice period in days</td><td><%= @user.notice%></td>
            </tr>
            <tr>
              <td>Emergency Contact Name</td><td><%= @user.ename%></td>
              <td>Relation</td><td><%= @user.relation%></td>
            </tr>
            <tr>
              <td>Emergency Contact Number</td><td><%= @user.econtact%></td>
              <td>Gender</td><td><%= @user.gender%></td>
            </tr>
            <tr>
              <td>Primary Skill</td><td><%= @user.pskill%></td>
              <td>Secondary Skill 1</td><td><%= @user.sskill1%></td>
            </tr>
            <tr>
              <td>Secondary Skill 2</td><td><%= @user.sskill2%></td>
              <td></td><td></td>
            </tr>
            <% if session[:type]=='admin'%>
            <tr>
              <td><%= link_to "Edit User", edit_user_path(@user)%></td>
              <td><%= link_to "Delete User", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}%></td><td></td><td></td>
            </tr>
            <% end%>
        </table>
      </div>

    <div class="footer" id="footer">
<pre><h4>EXALOGIC SOLUTIONS</h4>No 21, 1st Main, Ganga nagar, Bangalore
Karnataka, India - 560032<table align='center'>
<tr>
  <td><i class="fa fa-globe" aria-hidden="true">  </i></td><td><a href="http://www.exalogic.in/">www.exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-envelope" aria-hidden="true">  </i></td><td><a href="mailto:info@exalogic.in?subject=query">info@exalogic.in</a></td>
</tr>
<tr>
  <td><i class="fa fa-phone" aria-hidden="true">  </i></td><td><a href="tel:080- 48905017">080- 48905017</a></td>
</tr>
</table></pre>
<a href="#"><i class="fa fa-arrow-up fa-2x" aria-hidden="true"></i></a>
    </div>
  </body>

</html>